import { writeFileSync } from "node:fs";
import { labelConfirmationEmail } from "../supabase/functions/_shared/email-templates.ts";

const base = {
  publicCode: "ABC1234",
  carrierTracking: "1Z999AA10123456784",
  carrier: "USPS",
  eta: "3 business days",
  trackingUrl: "https://sendmo.co/t/ABC1234",
};

const variants: Array<{ title: string; subtitle: string; html: string }> = [
  {
    title: "full_label — all fields present",
    subtitle: "Buyer entered sender name, item description, paid price.",
    html: labelConfirmationEmail({
      ...base,
      senderName: "Jane Doe",
      itemDescription: "Vintage Pentax camera lens",
      displayPriceCents: 1247,
    }).html,
  },
  {
    title: "flex — full sender info",
    subtitle: "Flex sender entered name + item; server-derived amount.",
    html: labelConfirmationEmail({
      ...base,
      publicCode: "FLX5678",
      senderName: "Sam Carter",
      itemDescription: "Handmade ceramic mug — limited edition holiday set",
      displayPriceCents: 892,
    }).html,
  },
  {
    title: "flex — minimal sender info (no name)",
    subtitle: "Anonymous flex sender; item + amount only.",
    html: labelConfirmationEmail({
      ...base,
      publicCode: "FLX9999",
      senderName: null,
      itemDescription: "Birthday gift",
      displayPriceCents: 654,
    }).html,
  },
  {
    title: "legacy / missing item_description",
    subtitle: "Older shipment row — From + Amount render, Item row omitted.",
    html: labelConfirmationEmail({
      ...base,
      publicCode: "LEG0001",
      senderName: "Pat Lee",
      itemDescription: null,
      displayPriceCents: 1500,
    }).html,
  },
];

const wrap = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Label Confirmation Email — Variant Preview</title>
<style>
  body { margin:0; background:#e5e7eb; font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif; }
  .header { padding:24px 32px; background:#111827; color:#fff; }
  .header h1 { margin:0 0 4px; font-size:20px; }
  .header p { margin:0; font-size:13px; color:#9ca3af; }
  .variant { padding:24px 32px; border-top:1px solid #d1d5db; }
  .variant h2 { margin:0 0 4px; font-size:16px; color:#111827; }
  .variant p { margin:0 0 16px; font-size:13px; color:#4b5563; }
  iframe { width:100%; max-width:540px; height:720px; border:1px solid #d1d5db; border-radius:8px; background:#fff; }
</style>
</head>
<body>
<div class="header">
  <h1>labelConfirmationEmail — variant preview</h1>
  <p>Generated by scripts/render-label-email-preview.mts. Inspect each variant for From/Item/Amount row presence and visual fit.</p>
</div>
${variants
  .map(
    (v, i) => `
<div class="variant">
  <h2>${i + 1}. ${v.title}</h2>
  <p>${v.subtitle}</p>
  <iframe srcdoc="${v.html.replace(/"/g, "&quot;")}"></iframe>
</div>`,
  )
  .join("")}
</body>
</html>`;

writeFileSync(new URL("../previews/label-confirmation-email-variants.html", import.meta.url), wrap);
console.log("wrote previews/label-confirmation-email-variants.html");
